import * as constant from '../constant/DataVisualization'
import HXT from '../../../static/images/cmrj_hxt.png'
console.log(HXT)
const initialState = {
  dpLoading: false,
  ghLoading: false,
  zhLoading: false,
  clLoading: false,
  xqList: [],
  xqInfo: null,
  id: null,
  homePageTotal: {},
  pieList: {},
  barList: [],
  homeBuildList: [],
  homeUnitList: [],
  homeRoomList: [],
  homeResidentList: [],
  selectRecVehicleRecordList: [],
  homeBuildInfo: {},
  homeBuildTotal: {},  
  homeBuild: null,
  homeUnit: 'all',
  homeRoom: 'all',
  siderZHBuildList: [],
  siderZHBuildListJson: {},
  siderZHUnitList: [],
  siderZHRoomList: [],
  siderZHBuild: 'all',
  siderZHUnit: 'all',
  siderZHRoom: 'all',
  siderZHIdCard: undefined,
  siderZHType: 'all',
  siderZHInOutDateStart: undefined,
  siderZHInOutDateEnd: undefined,
  zhEntryAndExitList: [],
  siderCLBuildList: [],
  siderCLBuildListJson: {},
  siderCLUnitList: [],
  siderCLRoomList: [],
  siderCLBuild: 'all',
  siderCLUnit: 'all',
  siderCLRoom: 'all',
  siderCLIdCard: undefined,
  siderCLCarNumber: undefined,
  siderCLType: 'all',
  siderCLInOutDateStart: undefined,
  siderCLInOutDateEnd: undefined,
  clselectRecVehicleRecordList: [],
  homeHousingInfo: null,
  homePlayUrl: null,
  defaultPlayUrl1: null,
  // 'http://112.17.106.71:7086/live/cameraid/1000000%242/substream/1.m3u8',
  defaultPlayUrl2: null,
  // 'http://112.17.106.71:7086/live/cameraid/1000000%241/substream/1.m3u8',
  homePictureUrl: null,
  homeEntryAndExitList: [],
  homeBuildListJson: {},
  homeRoomListJson: {},
  servicesChannelList: [],
  residentListType: '',
  residentListParams: null,
  residentList: [],
  flow: '',
  residentListTitle: '',
  userTypeList: [],
  userTypeJson: {},
  siderResidentList: [],
  residentTogal: 0,
  GHTogal: 0,
  ZHTogal: 0,
  housingAddressList: [],
  fontServicesList: [],
  eqTotal: 0,
  HXTPictureUrl: HXT,
  roomLoading: false,
};

export default function DataVisualization(state = initialState, action = {}) {
  switch (action.type) {
      case constant.CHANGEV:
          return {
              ...state,
              ...action.payload,
          };
    default:
      return state;
  }
}